// @generated by protoc-gen-connect-query v0.2.3 with parameter "target=ts"
// @generated from file api.proto (package mindgraph, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateNodeRequest, Edge, Empty, HelloRequest, HelloResponse, ThemeRequest, VoteWordRequest } from "./api_pb.js";

export const typeName = "mindgraph.MindGraphService";

/**
 * @generated from rpc mindgraph.MindGraphService.Hello
 */
export const hello = createQueryService({
  service: {
    methods: {
      hello: {
        name: "Hello",
        kind: MethodKind.Unary,
        I: HelloRequest,
        O: HelloResponse,
      },
    },
    typeName: "mindgraph.MindGraphService",
  },
}).hello;

/**
 * @generated from rpc mindgraph.MindGraphService.SetTheme
 */
export const setTheme = createQueryService({
  service: {
    methods: {
      setTheme: {
        name: "SetTheme",
        kind: MethodKind.Unary,
        I: ThemeRequest,
        O: Empty,
      },
    },
    typeName: "mindgraph.MindGraphService",
  },
}).setTheme;

/**
 * @generated from rpc mindgraph.MindGraphService.CreateNode
 */
export const createNode = createQueryService({
  service: {
    methods: {
      createNode: {
        name: "CreateNode",
        kind: MethodKind.Unary,
        I: CreateNodeRequest,
        O: Empty,
      },
    },
    typeName: "mindgraph.MindGraphService",
  },
}).createNode;

/**
 * @generated from rpc mindgraph.MindGraphService.CreateEdge
 */
export const createEdge = createQueryService({
  service: {
    methods: {
      createEdge: {
        name: "CreateEdge",
        kind: MethodKind.Unary,
        I: Edge,
        O: Empty,
      },
    },
    typeName: "mindgraph.MindGraphService",
  },
}).createEdge;

/**
 * @generated from rpc mindgraph.MindGraphService.VoteWord
 */
export const voteWord = createQueryService({
  service: {
    methods: {
      voteWord: {
        name: "VoteWord",
        kind: MethodKind.Unary,
        I: VoteWordRequest,
        O: Empty,
      },
    },
    typeName: "mindgraph.MindGraphService",
  },
}).voteWord;
