// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=ts"
// @generated from file api.proto (package mindgraph, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateNodeRequest, Edge, Empty, Event, HelloRequest, HelloResponse, JoinRequest, ThemeRequest } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service mindgraph.MindGraphService
 */
export const MindGraphService = {
  typeName: "mindgraph.MindGraphService",
  methods: {
    /**
     * @generated from rpc mindgraph.MindGraphService.Hello
     */
    hello: {
      name: "Hello",
      I: HelloRequest,
      O: HelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mindgraph.MindGraphService.Join
     */
    join: {
      name: "Join",
      I: JoinRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc mindgraph.MindGraphService.SetTheme
     */
    setTheme: {
      name: "SetTheme",
      I: ThemeRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mindgraph.MindGraphService.CreateNode
     */
    createNode: {
      name: "CreateNode",
      I: CreateNodeRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mindgraph.MindGraphService.CreateEdge
     */
    createEdge: {
      name: "CreateEdge",
      I: Edge,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

