// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file api.proto (package mindgraph, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Event, HelloRequest, HelloResponse, JoinRequest } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service mindgraph.MindGraphService
 */
export const MindGraphService = {
  typeName: "mindgraph.MindGraphService",
  methods: {
    /**
     * @generated from rpc mindgraph.MindGraphService.Hello
     */
    hello: {
      name: "Hello",
      I: HelloRequest,
      O: HelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mindgraph.MindGraphService.Join
     */
    join: {
      name: "Join",
      I: JoinRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

