// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/itsp-pbl-2023/mind-graph/grpc/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// MindGraphServiceName is the fully-qualified name of the MindGraphService service.
	MindGraphServiceName = "mindgraph.MindGraphService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MindGraphServiceHelloProcedure is the fully-qualified name of the MindGraphService's Hello RPC.
	MindGraphServiceHelloProcedure = "/mindgraph.MindGraphService/Hello"
)

// MindGraphServiceClient is a client for the mindgraph.MindGraphService service.
type MindGraphServiceClient interface {
	Hello(context.Context, *connect_go.Request[pb.HelloRequest]) (*connect_go.Response[pb.HelloResponse], error)
}

// NewMindGraphServiceClient constructs a client for the mindgraph.MindGraphService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMindGraphServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) MindGraphServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &mindGraphServiceClient{
		hello: connect_go.NewClient[pb.HelloRequest, pb.HelloResponse](
			httpClient,
			baseURL+MindGraphServiceHelloProcedure,
			opts...,
		),
	}
}

// mindGraphServiceClient implements MindGraphServiceClient.
type mindGraphServiceClient struct {
	hello *connect_go.Client[pb.HelloRequest, pb.HelloResponse]
}

// Hello calls mindgraph.MindGraphService.Hello.
func (c *mindGraphServiceClient) Hello(ctx context.Context, req *connect_go.Request[pb.HelloRequest]) (*connect_go.Response[pb.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// MindGraphServiceHandler is an implementation of the mindgraph.MindGraphService service.
type MindGraphServiceHandler interface {
	Hello(context.Context, *connect_go.Request[pb.HelloRequest]) (*connect_go.Response[pb.HelloResponse], error)
}

// NewMindGraphServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMindGraphServiceHandler(svc MindGraphServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(MindGraphServiceHelloProcedure, connect_go.NewUnaryHandler(
		MindGraphServiceHelloProcedure,
		svc.Hello,
		opts...,
	))
	return "/mindgraph.MindGraphService/", mux
}

// UnimplementedMindGraphServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMindGraphServiceHandler struct{}

func (UnimplementedMindGraphServiceHandler) Hello(context.Context, *connect_go.Request[pb.HelloRequest]) (*connect_go.Response[pb.HelloResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("mindgraph.MindGraphService.Hello is not implemented"))
}
